INSERT INTO tb_user (name, address, email, password) VALUES ('Alex', 'Rua do Campo, Bairro Alvorada', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, address, email, password) VALUES ('Maria', 'Rua das Flores, Bairro Primavera', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Hamburger de Siri', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 40.00, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/hamburger.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Hamburger com Bacon', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 42.75, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/hamburger.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Hamburger com Queijo', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 35.00, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/hamburger.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Hamburger Vegano', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 55.80, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/hamburger.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Sopa de Legumes', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 22.00, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/sopa.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Sopa de Tainha', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 25.00, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/sopa.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Sopa de Brócolis', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 31.50, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/sopa.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Pizza Calabresa', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 83.75, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/pizza.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Pizza Portuguesa', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 62.00, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/pizza.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Pizza Marguerita', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 75.00, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/pizza.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Pizza Quatro Queijos', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 60.25, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/pizza.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Refrigerante Pureza', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 3.50, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/coca.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Refrigerante Coca Cola', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 5.00, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/coca.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Refrigerante Tubaína', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 4.75, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/coca.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Suco de Laranja', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 8.00, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/suco.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Suco de Uva', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 8.00, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/suco.jpg');

INSERT INTO tb_product (name, description, price, img_url) VALUES ('Suco de Acerola', 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for will uncover many web sites still in their infancy.', 8.00, 'https://raw.githubusercontent.com/dmrsilva/delivery-system/main/frontweb/src/assets/images/suco.jpg');

INSERT INTO tb_order (moment, status) VALUES (TIMESTAMP WITH TIME ZONE '2022-05-10T18:25:20.12345Z', 2);
INSERT INTO tb_order (moment, status) VALUES (TIMESTAMP WITH TIME ZONE '2022-05-10T20:30:10.12345Z', 1);
INSERT INTO tb_order (moment, status) VALUES (TIMESTAMP WITH TIME ZONE '2022-05-10T20:30:10.12345Z', 0);

INSERT INTO tb_order_product(order_id, product_id) VALUES (1, 2);
INSERT INTO tb_order_product(order_id, product_id) VALUES (1, 13);

INSERT INTO tb_order_product(order_id, product_id) VALUES (2, 8);
INSERT INTO tb_order_product(order_id, product_id) VALUES (2, 12);

INSERT INTO tb_order_product(order_id, product_id) VALUES (3, 6);